// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using twAspnet.Models;

namespace twAspnet.Migrations
{
    [DbContext(typeof(TwaspDbContext))]
    [Migration("20200118125943_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("twAspnet.Models.Enviroment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ASecretKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("AToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("ATokenSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("Akey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Enviroment");
                });

            modelBuilder.Entity("twAspnet.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Favoritedate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tweet")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("twAspnet.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Regdate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
